name: CI

on:
  push:
    branches: [ main, monorepo-migration ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Load test environment
        run: |
          if [ -f .env.test ]; then cat .env.test >> $GITHUB_ENV; fi
          if [ -f backend/.env.test ]; then cat backend/.env.test >> $GITHUB_ENV; fi

      - name: Run backend tests
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          pytest tests/backend/ -v

      - name: Test API endpoints
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          python3 tests/backend/test_endpoints.py

